name: JIT_Access
description: Policy for admin JIT for microsoft-graph-explorer-v4 repo

resource: repository

configuration:
  jitAccess:
    enabled: true
    maxHours: 2
    approvers:
    requestors:
      role: write