version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  target-branch: "dependabot-upgrades"
  schedule:
    interval: monthly
  open-pull-requests-limit: 20
- package-ecosystem: "github-actions"
  directory: "/"
  groups:
    github-actions:
      patterns: ["*"]
  schedule:
    interval: "weekly"
  cooldown:
    default-days: 7
