declare module 'react-intl';
declare module 'react-intl/locale-data/zh';
declare module 'react-intl/locale-data/ja';
declare module 'react-intl/locale-data/pt';
declare module 'react-intl/locale-data/ru';
declare module 'react-intl/locale-data/fr';
declare module 'react-intl/locale-data/es';
declare module 'react-intl/locale-data/en';
declare module 'react-intl/locale-data/de';