// Theme generated from https://developer.microsoft.com/en-us/fabric#/styles/themegenerator
import { webDarkTheme } from '@fluentui/react-components';

export const darkTheme = {
  ...webDarkTheme,
  colorBrandBackground: '#2196f0',
  colorBrandBackgroundHover: '#37a0f1',
  colorBrandBackgroundPressed: '#54aef3',
  colorNeutralBackground1: '#121212',
  colorNeutralBackground2: '#1c1c1c',
  colorNeutralBackground3: '#2c2c2c',
  colorNeutralBackground4: '#353535',
  colorNeutralBackground5: '#3d3d3d',
  colorNeutralForeground1: '#fdfdfd',
  colorNeutralForeground2: '#fefefe',
  colorNeutralForeground3: '#fefefe',
  colorNeutralForeground4: '#fdfcfc',
  colorNeutralForegroundDisabled: '#5e5e5e',
  colorNeutralForegroundInverted: '#ffffff',
  colorNeutralForegroundInvertedDisabled: '#070707',
  colorBrandForegroundLink: '#6cb8f6',
  colorBrandForegroundLinkHover: '#00a100',
  colorNeutralForegroundInvertedLink: '#f3f2f1',
  colorNeutralBackgroundInverted: '#1b1a19',
  colorNeutralForegroundInvertedIcon: '#c8c6c4',
  colorPaletteRedBackground3: '#442726',
  colorPaletteRedForeground3: '#f1707b',
  colorPaletteRedBorder3: '#442726',
  colorPaletteRedIcon3: '#f1707b',
  colorPaletteOrangeBackground3: '#4f2a0f',
  colorPaletteOrangeForeground3: '#fce100',
  colorPaletteGreenBackground3: '#393d1b',
  colorPaletteGreenForeground3: '#92c353',
  colorPaletteYellowBackground3: '#433519',
  colorPaletteYellowForeground3: '#c8c6c4'
};
