export const QUERY_GRAPH_SUCCESS = 'QUERY_GRAPH_SUCCESS';
export const QUERY_GRAPH_ERROR = 'QUERY_GRAPH_ERROR';
export const GET_AUTH_TOKEN_SUCCESS = 'GET_AUTH_TOKEN_SUCCESS';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
